openapi: 3.0.0
info:
  title: Payment API
  version: '1.1'
  description: Payment System API for Final Year Project implementation
  contact:
    name: Patryk Rojowiec
servers: 
  - url: ''
paths:
  '/payment':
    post:
      summary: Pay a user
      operationId: post-payment
      responses:
        '200':
          description: Money transferred successfully - User has been credited
        '400':
          description: Bad Request - Missing or incorrect values in the data
        '401':
          description: Unauthorized
      description: Executed by system after user completes and enters their user data, allows payments to be made
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment'
            example:
              username: John Smith
              number: 0851234567
              amount: 1.70
        description: This is the info that the user sends to allow a transaction
      tags:
        - POST
      security:
        - JWTauthorization: []
  '/stations/login':
    get:
      summary: Log in machine
      tags:
        - GET
      responses:
        '200':
          description: Machine logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Login token sent after successful connection to API
                    example: >-
                      eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYjhjZDNkNTUtYzNiYy00ZjE5LWIzZjktM2QzZjkyZDE5MmQ0IiwicGFzc3dvcmQiOiIkMmEkMTIkTFFmNGw3QUl0Z2hTZ2hRalpWSzZET3Vab1cwbkZjbVloSExTMmdOeHo0NUF0NHN0cjZLSWkifSwiaWF0IjoxNjQ4OTE2NjI3LCJleHAiOjE2NDkwODk0Mjd9.RsdNrdCHnUMZzIjj9OFZHhqZ8JGDx9YrwVYKeZp_068
                  id:
                    type: string
                    description: The requesting stations ID
                    example: b8cd3d55-c3bc-4f19-b3f9-3d3f92d192d4
                required:
                  - token
                  - id
        '401':
          description: Incorrect machine credentials
      description: >-
        Returns a JWT to the requesting machine once correct credentials are supplied. This authorizes the machine to perform transactions to the system
      parameters: []
      security:
        - HTTPBasic: []
    parameters: []
tags:
  - name: POST
components:
  schemas:
    Payment:
      title: Payment
      type: object
      description: ''
      x-examples:
        example:
          username: John Smith
          number: 0851234567
          amount: 1.70
      properties:
        username:
          type: string
          description: Name of the user
          example: John Smith
        number:
          type: string
          minLength: 10
          maxLength: 10
          description: Phone number of the user
          example: 0851234567
        amount:
          type: number
          description: amount of money from cans
          example: 1.70
      required:
        - username
        - number
        - amount
  securitySchemes:
    HTTPBasic:
      type: http
      scheme: basic
    JWTauthorization:
      type: http
      scheme: bearer